#!/usr/bin/env python3
# Copyright (c) 2025 Huawei Technologies Co., Ltd.
#
# Convert HCCL allgather debug dumps to a PyTorch .pt file.

import argparse
from pathlib import Path

import torch


DTYPE_MAP = {
    "int8": torch.int8,
    "int16": torch.int16,
    "int32": torch.int32,
    "int64": torch.int64,
    "uint8": torch.uint8,
    "uint16": torch.uint16,
    "uint32": torch.uint32,
    "uint64": torch.uint64,
    "float16": torch.float16,
    "float32": torch.float32,
    "float64": torch.float64,
    "bfloat16": torch.bfloat16,
}


def parse_dump(path: Path):
    raw = path.read_bytes()
    marker = b"\ndata\n"
    header_end = raw.find(marker)
    if header_end < 0:
        raise ValueError(f"{path} is not an HCCL allgather dump")

    header = raw[:header_end].decode("utf-8")
    data = raw[header_end + len(marker):]
    lines = header.splitlines()
    if not lines or lines[0] != "HCCL_ALLGATHER_DUMP_V1":
        raise ValueError(f"{path} has unsupported dump format")

    meta = {}
    for line in lines[1:]:
        key, value = line.split("=", 1)
        meta[key] = value
    return meta, data


def build_tensor(meta, data):
    dtype_name = meta["dtype"]
    if dtype_name not in DTYPE_MAP:
        raise ValueError(f"unsupported dtype: {dtype_name}")

    tensor = torch.frombuffer(bytearray(data), dtype=DTYPE_MAP[dtype_name])
    count = int(meta["count"])
    if tensor.numel() != count:
        raise ValueError(f"data element count mismatch: header={count}, actual={tensor.numel()}")

    rank_size = int(meta["rank_size"])
    if meta.get("stage") == "output" and rank_size > 0 and count % rank_size == 0:
        tensor = tensor.reshape(rank_size, count // rank_size)
    return tensor.clone()


def main():
    parser = argparse.ArgumentParser(description="Convert HCCL allgather dump to torch .pt")
    parser.add_argument("dump", type=Path, help="dump file generated by HCCL allgather debug dump")
    parser.add_argument("-o", "--output", type=Path, help="output .pt path")
    args = parser.parse_args()

    meta, data = parse_dump(args.dump)
    tensor = build_tensor(meta, data)
    output = args.output or args.dump.with_suffix(".torch.pt")
    torch.save({"tensor": tensor, "meta": meta}, output)
    print(output)


if __name__ == "__main__":
    main()
